#!/usr/bin/env php
<?php

namespace think;

define('DS', DIRECTORY_SEPARATOR);
define('ROOT_PATH', __DIR__ . '/../');

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 应用初始化
(new App())->console->run();